CREATE TABLE daily_expenses (
    id INT AUTO_INCREMENT PRIMARY KEY,
  Expense_Id VARCHAR(255) NOT NULL UNIQUE,
  Expense_Date DATE NOT NULL,

  Category VARCHAR(255) NOT NULL,
  Product_Description VARCHAR(255) NOT NULL,
  Notes TEXT,
  Amount DECIMAL(10,2) NOT NULL,

  Created_By VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

);
