CREATE TABLE pre_booked_order_items  (
  
   

    id INT PRIMARY KEY AUTO_INCREMENT,
    Pre_Booked_Order_Item_Id VARCHAR(255) NOT NULL UNIQUE,
    Pre_Booked_Order_Id VARCHAR(255) NOT NULL,
    Item_Id VARCHAR(255) NOT NULL,
    Quantity INT NOT NULL DEFAULT 1,
    Price DECIMAL(10,2) NOT NULL,
    Amount DECIMAL(10,2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
   
);